In [ ]:

Write a Python Program to Add Two Matrices?

In [10]:
import numpy as np 
def add_matrices(a,b):
    a = np.array(a)
    b = np.array(b) 
    try :
        return np.add(a,b)
    except Exception as e :
        return e 
array1 = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]

array2 = [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]]
print(add_matrices(array1,array2))
array1 = [[1, 2, 3],
          [4, 5, 6]]

array2 = [[7, 8],
          [9, 10],
          [11, 12]]
print(add_matrices(array1,array2))

[[11 13 15]
 [17 19 21]
 [23 25 27]]
operands could not be broadcast together with shapes (2,3) (3,2) 


In [ ]:
Write a Python Program to Multiply Two Matrices?

In [14]:

# Program to multiply two matrices using nested loops
 
# take a 3x3 matrix
A = [[12, 7, 3],
    [4, 5, 6],
    [7, 8, 9]]
 
# take a 3x4 matrix   
B = [[5, 8, 1, 2],
    [6, 7, 3, 0],
    [4, 5, 9, 1]]
     
result = [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]
 
# iterating by row of A
for i in range(len(A)):
 
    # iterating by column by B
    for j in range(len(B[0])):
 
        # iterating by rows of B
        for k in range(len(B)):
            result[i][j] += A[i][k] * B[k][j]
            
for r in result:
    print(r)

[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


In [ ]:
Write a Python Program to Transpose a Matrix?

In [15]:
array1 = [[1, 2, 3],
          [4, 5, 6]]
array1 = np.transpose(np.array(array1))
array1 

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
Write a Python Program to Sort Words in Alphabetic Order?

In [1]:
words=["cat","dog","ant"]
words.sort()

In [ ]:
Write a Python Program to Remove Punctuation From a String?

In [2]:
import string

# The string to be cleaned
s = '!@$#%^TFDGHehsgWRU$%%'

# Use a list comprehension to remove all punctuation from the string
cleaned = ''.join(c for c in s if c not in string.punctuation)

print(cleaned)

TFDGHehsgWRU
